### ISSUE TITLE
Disabling Efficiency Mode can greatly improve Firefox performance on Windows 11

### ISSUE THREAD

**Issue by gunir** [yokoffing/Betterfox#310] opened 2024-07-30 07:08 UTC
By default Efficiency Mode is throttling Firefox, anything that try to save battery works just by throttling applications, unless the application itself disables some of its features to do that, there's no magic behind it. To disable it:
- Go to `about:config`
- Type `dom.ipc.processPriorityManager.backgroundUsesEcoQoS` -> `+` to create -> set to `false`

[A lot of users confirmed that Firefox runs much faster after disabling it](https://old.reddit.com/r/firefox/comments/107fj69/how_can_i_disable_the_efficiency_mode_on_firefox/j3mc43t/)

Source: https://old.reddit.com/r/firefox/comments/1efmvvk/if_youre_using_windows_11_and_firefox_is_laggy/

**Comment by t6rtar** [comment] 2024-07-31 01:23
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by yokoffing** [comment] 2024-07-31 19:30
https://github.com/yokoffing/Betterfox/blob/29f081696200afc3af6a43f300a8000af18fa86e/Fastfox.js#L58-L66

**Comment by gunir** [comment] 2024-08-04 05:18
I hope more users will test this and send feedback, so far I've seen only positive result from people who disable Efficiency Mode, I believe it's just another garbage technology made by Microsoft, so far only Edge benefit from this to some extends.

**Comment by yokoffing** [comment] 2024-08-10 01:48
> [A lot of users confirmed that Firefox runs much faster after disabling it](https://old.reddit.com/r/firefox/comments/107fj69/how_can_i_disable_the_efficiency_mode_on_firefox/j3mc43t/)

There were further optimizations made soon after this post. I remember this Reddit post lol.

> https://old.reddit.com/r/firefox/comments/1efmvvk/if_youre_using_windows_11_and_firefox_is_laggy/lfyglyv/

This comment is interesting. I haven't tried gaming and running a video on a duel monitor setup.

With normal use (general browsing on one monitor), I've tested disabling Efficiency Mode on both low-end and high-end Windows machines, and I can't tell a difference either way.

**Comment by gunir** [comment] 2024-08-10 02:29
> There were further optimizations made soon after this post. I remember this Reddit post lol.

> This comment is interesting. I haven't tried gaming and running a video on a duel monitor setup.

I can't trust the quality of Microsoft post-BG, Windows did an update that makes Windows auto-update BIOS, which broke computer of a lot of users.
Like [this](https://old.reddit.com/r/firefox/comments/12hxqjl/microsoft_fixes_5yearold_windows_defender_bug/), so many people are still experience slow down after their patch or it didn't completely fix this issue as there's some disscussion in Bugzilla of Firefox devs following in the closed bug.

**Comment by Feejus** [comment] 2024-08-10 09:53
I made an observation. I need to try this to confirm it on my setup, but what i am seeing is an increase RAM use by Firefox when this is turned off. Has anyone else seen this or could it be my setup / firefox version i am running (beta) 130b3. 

I am going to turn this off and look at memory utilisation. However i would like to get your view on this matter as this could be isolated to me. 

Thanx

**Comment by Feejus** [comment] 2024-08-10 12:41
Just to drop a message. I can confirm my findings. Turning the "dom.ipc.processPriorityManager.backgroundUsesEcoQoS" to false increase my firefox memory utilisation to 4x. I have not noticed any additional speed with our without on my Intel 12th gen NUC. Maybe this has major impact on lower end hardware. 

Firefox currently open and have 89 open tabs. Memory is about 1.5 gig instead of the 6 -10 gig. 

I would be keen to know if anyone else notice this difference in memory utilization.

**Comment by philg-dev** [comment] 2024-08-10 13:31
@Feejus

Just some thoughts about the RAM usage:

1.5 GiB for 89 open tabs is basically "impossible" **if all those tabs are actually loaded**.
I use Simple Tab Groups, which always shows how many tabs of each group are actually in-memory and how many are just "sitting there" on disk in the cold session storage. You can also check which tabs are actually loaded in the `about:processes` page. That page also lets you discard tabs without closing them - which sometimes is useful when a lot of "trash" has accumulated in RAM from a tab (e.g. my Twitch tab frequently uses up 800~900 MiB after a while, but when I discard and reload it, the RAM usage goes down to about 350 MiB).

**It would be interesting to know** if the `backgroundUsesEcoQoS` property changes the way Firefox automatically discards tabs. Discarding a tab will just free up it's memory and CPU usage, since it's unloaded, but not closed. You might have noticed this behavior when switching to a tab that was still open after restarting firefox - the tab usually loads on-demand in that case.

I've never witnessed any tabs being discarded automatically on my end. I'm not on Windows 11 though. But from what you describe regarding your tests in terms of RAM usage, my assumption would be that `backgroundUsesEcoQoS` somehow allows for automatic discarding of tabs.

**Comment by Feejus** [comment] 2024-08-10 13:44
@philg-dev
Thank you for your insightful comment. I'd like to clarify that I never claimed the tabs were fully loaded; I only mentioned they were open. I appreciate you reminding me about the about:processes function, which I had forgotten.

Your point about the backgroundUsesEcoQoS property potentially affecting how Firefox automatically discards tabs is particularly interesting. This is exactly why I was eager to get different perspectives on the matter.

Moving forward, I plan to run my PC with Firefox open for several days to observe its memory usage. I'll adjust the settings and monitor how it behaves under different conditions.

Thank you

**Comment by philg-dev** [comment] 2024-08-10 14:37
@Feejus yes - I know you didn't claim that, don't worry :-)

I just wanted to clarify the behavior as I know it. I'm very used to freeing up my RAM manually via either Simple Tab Groups "Discard Tab" / "Discard Group" function or directly via `about:processes`. That's why it was important for me to explain the details

Looking forward to your test results :+1:

**Comment by gunir** [comment] 2024-08-11 12:49
> I made an observation. I need to try this to confirm it on my setup, but what i am seeing is an increase RAM use by Firefox when this is turned off. Has anyone else seen this or could it be my setup / firefox version i am running (beta) 130b3.
> 
> I am going to turn this off and look at memory utilisation. However i would like to get your view on this matter as this could be isolated to me.
> 
> Thanx

Windows 10 doesn't have Efficiency Mode and doesn't have any issue with RAM so far.

The question is how much RAM do you have, if you have a lot Firefox will try to use a lot.

The best way to debug RAM is to use `about:memory`, Measure and Compare between false and true

**Comment by AuRiMaS666** [comment] 2024-08-18 13:30
My impressions are quite similar after running with Efficiency Mode mode OFF and ON for a few months or weeks each. RAM usage is definitely higher with it OFF, but overall performance and snappiness, couldn't honestly tell if there is much of a difference.

**Comment by Feejus** [comment] 2024-08-18 13:59
My observations
D
I have observed double amount of RAM usage. Also on the question of how much ram I got, machine is Intel NUC 12 with 64gb of ram. Running it in off mode I did not notice any difference between on or off.

**Comment by yokoffing** [comment] 2024-08-21 23:09
Thanks for the good discussion, everyone.

**Closed by yokoffing** 2024-08-21 23:09 UTC

**Comment by HenryTheVacuum** [comment] 2024-11-20 16:07
It's night and day if you turn it off while using tabs that are 500mb+ and use any cpu/gpu.

If I keep it enabled and try to use multiple tabs with TradingView.com (stock charting website) there is a huge lag in switching tabs.
